on:
  push:
    branches:
      - main
  pull_request:
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
        with:
          node-version: ${{ matrix.node }}
      - run: node --version
      # The first installation step ensures that all of our production
      # dependencies work on the given Node.js version, this helps us find
      # dependencies that don't match our engines field:
      - run: npm install --production --engine-strict --ignore-scripts --no-package-lock
      # Clean up the production install, before installing dev/production:
      - run: rm -rf node_modules
      - run: npm install
      - run: npm test
